import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import bg from "../public/sprinkle.svg";
import Navbar from "../components/navbar";
import pic from "../public/head.jpg";
const inter = Inter({ subsets: ["latin"] });
import { Link as LinkS } from "react-scroll";

export default function Home() {
  return (
    <div className="">
      <Navbar />

      <Head>
        <title>ToDo it</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className="flex h-full p-4 top bg-bg pb-[50px]">

    <div className="right mt-[-50px]">
         <h1 className="text-8xl ml-[100px] mt-[200px]">ToDo It</h1>
         <br /><br />
      <p className="ml-[100px] text-3xl">
        Simply and smartly manage your projects and ideas at one place.
      </p>
      <br />
      <br />
      <div className="flex gap-[30px] txt">
        <a
          href="/signin"
          className="px-5  bg-main p-3 rounded-xl ml-[100px] text-white"
        >
          Start your todo-it journey now !
        </a>
        <a href="" className="p-3 border-2 border-main ">
          See more
        </a>
      </div>
      

    </div>
    <Image src={pic} height={300} width={750} className="mt-[50px] rounded-md"></Image>

      </div>
      
    </div>
  );
}
